# Generated by Django 3.1.5 on 2021-01-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210111_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('pdf', 'pdf'), ('image', 'image'), ('word', 'word'), ('powerpoint', 'powerpoint'), ('excel', 'excel'), ('html', 'html')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Document_type',
        ),
    ]
